import { useEffect } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount } from "wagmi";
import axios from "axios";

const Home: NextPage = () => {
  const { isConnected, address } = useAccount();

  // * make this on click instead of useffect, then use the cookie for fetching the user-data route though token
  useEffect(() => {
    const handleConnect = async () => {
      if (isConnected) {
        try {
          const resp = await axios.post(
            `${process.env.NEXT_PUBLIC_DOMAIN}/api/authenticate`,
            { wallet_address: address }
          );
          console.log("Authentication response:", resp.data);
        } catch (error) {
          console.error("Error authenticating:", error);
        }
      } else {
        console.log("No account found");
      }
    };
    handleConnect();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* Remaining JSX content */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
